# this file has been generated automatically
# Geometry
export TOPO_SOURCE=gmted2010
export VERT_DISC=vfd
export DOMAIN=AROME_2.5
export LGRADSP=yes
export VLEV=65
export GRID_TYPE=LINEAR
# EDA
export SCALE_PERT=no
export EREF=35000
export PERTATMO=ECMAIN
export PERTSURF=none
export FESTAT=no
# Postprocessing
export FLDEXTR=yes
export FREQ_RESET_GUST=1
export RCR_POSTP=no
export FLDEXTR_TASK=1
export FLDVER_HOURS=06 12 18 24 30 36 42 48
export OBSMONITOR=obstat
export VFLDEXP=$EXP
export IO_SERVER=no
export IO_SERVER_BD=no
export OBSEXTR=yes
export POSTP=inline
export FREQ_RESET_TEMP=0
export FIELDMONITOR=no
export FLDVER=no
# Nesting
export LUNBC=yes
export HOST_MODEL=ifs
export SURFEX_INPUT_FORMAT=lfi
export BDINT=1
export BDSTRATEGY=RCR_operational
export LSPBDC=no
export NATIVE_INPUT_LFI=no
export HOST_SURFEX=no
# Physics
export HARATU=yes
export MASS_FLUX_SCHEME=edmfm
export XRIMAX=0
export DYNAMICS=nh
export STATNW=yes
export PHYSICS=arome
# Aux
export USE_MSG=no
export JB_INTERPOL=no
export SINGLEOBS=no
export MAKEODB2=no
# Archiving
export CONVERTFA=yes
export MAKEGRIB_LISTENERS=1
export ARCHIVE_FORMAT=GRIB1
export NCNAMES=nwp
export ARSTRATEGY=climate:fg:verif:odb_stuff:[an|fc]_fa:pp_grb
export RCR_POSTP=no
# Paths
export BDCLIM=$HM_DATA/${BDLIB}/climate
export ARCHIVE_ROOT=$HM_DATA/archive
export EXTRARCH=$ARCHIVE_ROOT/extract
export OBDIR=$HMDATA/observations
export BINDIR=$HM_DATA/bin
export CLIMDIR=$HM_DATA/climate
export BDDIR=$HM_DATA/${BDLIB}/archive/@YYYY@/@MM@/@DD@/@HH@
export INT_BDFILE=$WRK/ELSCF${CNMEXP}ALBC@NNN@
export MAPBIN=$HM_DATA/lib/util/mapbin
export ECFSLOC=ectmp
export ECFS_EPS_EC_BD_PATH=${ECFSLOC}:/$USER/harmonie/$EXP
export WRK=$HM_DATA/$CYCLEDIR
export MSG_PATH=$SCRATCH/CLOUDS/
# DFI
export TAUS=5400
export TSPAN=5400
export DFI=none
# System
export ECFSGROUP=hirald
export MULTITASK=no
export RUNNING_MODE=research
export NAMELIST_BASE=harmonie
export SIMULATION_TYPE=nwp
export BDLIB=ECMWF
export CNMEXP=HARM
# Assimilation
export INCV=1,1,1,1
export ANAATMO=3DVAR
export ILRES=2,2
export NOUTERLOOP=2
export ANASURF_MODE=before
export LSMIXBC=yes
export TSTEP4D=120,120
export ANASURF=CANARI_OI_MAIN
export INCO=1,1,0
# Surfex
export CISBA=3-L
export SURFEX_SEA_ICE=none
export SURFEX_OUTPUT_FORMAT=fa
export NPATCH=1
export LISBA_CANOPY=.TRUE.
export ECOCLIMAP_VERSION=2.5_plus
export MODIFY_LAKES=F
export CROUGH=NONE
export LDB_VERSION=3.0
export SOIL_TEXTURE_VERSION=FAO
export SURFEX_LAKES=WATFLX
export CSNOW=3-L
# Times
export SURFEX_LSELECT=yes
export FULLFAFTIMES=$HWRITUPTIMES
export SFXSWFTIMES=-1
export SFXSELTIMES=$PWRITUPTIMES
export PWRITUPTIMES=00-60:3
export PFFULLWFTIMES=-1
export HWRITUPTIMES=00-21:3,24-60:6
export VERITIMES=00-60:1
export INT_SINI_FILE=$WRK/SURFXINI.fa
export SFXWFTIMES=$SWRITUPTIMES
export HH_LIST=00-21:03
export SWRITUPTIMES=00-06:3
export LL_LIST=12,3
