# this file has been generated automatically
# Geometry
export TOPO_SOURCE=gmted2010
export VERT_DISC=vfd
export DOMAIN=Dict{String,Any}("NLAT"=>150,"LONC"=>14.8,"TSTEP"=>240,"GSIZE"=>10000,"LON0"=>20,"LATC"=>51.9,"LAT0"=>50.2,"NLON"=>150,"NAME"=>"TRAINING_10")
export LGRADSP=yes
export VLEV=65
export GRID_TYPE=LINEAR
# EDA
export SCALE_PERT=no
export EREF=35000
export PERTATMO=ECMAIN
export PERTSURF=none
export FESTAT=no
# Main
export DTGEND=
export DTGBEG=
export MAIL_ON_ABORT=Any[]
export PATHS=Dict{String,Any}("BDCLIM"=>"\$HM_DATA/\${BDLIB}/climate","ARCHIVE_ROOT"=>"\$HM_DATA/archive","EXTRARCH"=>"\$ARCHIVE_ROOT/extract","OBDIR"=>"\$HMDATA/observations","BINDIR"=>"\$HM_DATA/bin","CLIMDIR"=>"\$HM_DATA/climate","BDDIR"=>"\$HM_DATA/\${BDLIB}/archive/@YYYY@/@MM@/@DD@/@HH@","INT_BDFILE"=>"\$WRK/ELSCF\${CNMEXP}ALBC@NNN@","MAPBIN"=>"\$HM_DATA/lib/util/mapbin","ECFSLOC"=>"ectmp","ECFS_EPS_EC_BD_PATH"=>"\${ECFSLOC}:/\$USER/harmonie/\$EXP","WRK"=>"\$HM_DATA/\$CYCLEDIR","MSG_PATH"=>"\$SCRATCH/CLOUDS/")
export GITBRANCH=Dict{String,Any}("name"=>"cy43","commit"=>Dict{String,Any}("sha"=>"571811786e682e586a9c732bc30cdde44448d9ba","url"=>"https://api.github.com/repos/roelstappers/hm_home/commits/571811786e682e586a9c732bc30cdde44448d9ba"))
export GITURL=https://github.com/roelstappers/hm_home/
# Postprocessing
export ARCHIVE_FORMAT=GRIB2
export FLDEXTR=yes
export FREQ_RESET_GUST=1
export RCR_POSTP=no
export FLDEXTR_TASK=1
export FLDVER_HOURS=06 12 18 24 30 36 42 48
export OBSMONITOR=obstat
export VFLDEXP=$EXP
export IO_SERVER=no
export MAKEGRIB_LISTENERS=1
export IO_SERVER_BD=no
export OBSEXTR=yes
export CONVERTFA=yes
export NCNAMES=nwp
export POSTP=inline
export FREQ_RESET_TEMP=0
export FIELDMONITOR=no
export FLDVER=no
# Nesting
export LUNBC=yes
export HOST_MODEL=ifs
export SURFEX_INPUT_FORMAT=lfi
export BDINT=1
export BDSTRATEGY=RCR_operational
export LSPBDC=no
export NATIVE_INPUT_LFI=no
export HOST_SURFEX=no
# Physics
export HARATU=true
export MASS_FLUX_SCHEME=edmfm
export DYNAMICS=nh
export PHYSICS=arome
# EPS
# Observations
export IASI_OBS=0
export LIMB_OBS=0
export AIRCRAFT_OBS=1
export PILOT_OBS=1
export TEMP_OBS=1
export SYNOP_OBS=1
export BOUY_OBS=1
export MODESEHS_OBS=0
export RADAR_OBS=0
export SEV_OBS=0
export AMSUA_OBS=0
export SCATT_OBS=0
export LISTE_LOC=Any[]
export AMSUB_OBS=0
export SEVIRI_OBS=0
export GNSS_OBS=0
export CRIS_OBS=0
export ATMS_OBS=0
export AMV_OBS=0
export SGNSS_OBS=0
export PAOB_OBS=0
# Aux
export USE_MSG=no
export JB_INTERPOL=no
export SINGLEOBS=no
export MAKEODB2=no
# Archiving
# System
export ECFSGROUP=hirald
export MULTITASK=no
export RUNNING_MODE=research
export hostdescriptions=Dict{String,Any}("HM_DATA1"=>"","HM_LIB0"=>"","DTGEND"=>"","DTGBEG"=>"","HM_LIB1"=>"","PLAYFILE"=>"harmonie","BUILD"=>"yes","HM_DATA0"=>"")
export NAMELIST_BASE=harmonie
export SIMULATION_TYPE=nwp
export BDLIB=ECMWF
export ARSTRATEGY=medium
export Config=Dict{String,Any}("JOBOUTDIR"=>"\$HM_DATA/sms_logfiles","GMTED2010_INPUT_PATH"=>"\$HM_CLDATA/GMTED","PATH"=>".:\$HM_LIB/scr:\$HM_LIB/msms:\$HM_LIB:\$GMKROOT/util:\$PATH","HM_DATA"=>"\$HOME/scratch/hm_home/\$EXP","HARMONIE_CONFIG"=>"linuxgfortran","LD_LIBRARY_PATH"=>"\$LD_LIBRARY_PATH:\${HM_LIB}/util/grib_api/fortran/.libs:\${HM_LIB}/util/grib_api/src/.libs","L_GATHERV_WRGP"=>".FALSE.","CDP"=>"\${CDP-\$HM_LIB/msms/sms_cdp}","MAKE"=>"make","MAKEUP_BUILD_DIR"=>"\$HM_LIB","PERL_TK"=>"perl","HM_LIB"=>"\$HM_DATA/lib","ROOTPACK"=>"\$HM_DATA/../rootpack","BUFR_TABLES"=>"\$HM_LIB/util/auxlibs/bufr_405/bufrtables/","MKDIR"=>"mkdir -p","MAKE_OWN_PRECOMPILED"=>"no","GMKROOT"=>"\$HM_LIB/util/gmkpack","COMPCENTRE "=>"LOCAL","GRIB_TEMPLATES_PATH"=>"\$HM_LIB/util/grib_api/samples","GRIB_DEFINITION_PATH"=>"\$HM_LIB/util/gl_grib_api/definitions:\$HM_LIB/util/grib_api/definitions","MAKEUP"=>"yes","LMPOFF"=>".TRUE.","PERLTKDIR"=>"","GMKTMP"=>"/tmp","HM_COMDAT"=>"\$HM_DATA/..","MAKEUP_BUILD_GRIB_API_FLAG"=>"-A","RSYNC_EXCLUDE"=>"'--exclude=.svn'","GRIB_SAMPLES_PATH"=>"\$HM_LIB/util/grib_api/samples","HOST0"=>"`hostname`","HOST_INSTALL"=>"0","HM_CLDATA"=>"\$HOME/climdata","GMKFILE"=>"GFORTRAN.LINUX","SMSHOST"=>"\${SMSHOST-\$HOST0}")
export CNMEXP=HARM
# Assimilation
export INCV=1,1,1,1
export ANAATMO=3DVAR
export ANASURF_MODE=before
export LSMIXBC=yes
export ANASURF=CANARI_OI_MAIN
export INCO=1,1,0
# Surfex
export CISBA=3-L
export SURFEX_SEA_ICE=none
export SURFEX_OUTPUT_FORMAT=fa
export NPATCH=1
export LISBA_CANOPY=.TRUE.
export ECOCLIMAP_VERSION=2.5_plus
export NAMELIST=Dict{String,Any}("NAM_TEB"=>Dict{String,Any}(),"NAM_SSOn"=>Dict{String,Any}())
export MODIFY_LAKES=F
export CROUGH=NONE
export LDB_VERSION=3.0
export SOIL_TEXTURE_VERSION=FAO
export SURFEX_LAKES=WATFLX
export CSNOW=3-L
# ecflow
export Date=Dict{String,Any}("Hour"=>Dict{String,Any}("Cycle"=>Dict{String,Any}("StartData"=>Dict{String,Any}(),"Analysis"=>Dict{String,Any}("AnSFC"=>Dict{String,Any}("Canari"=>Dict{String,Any}("Namelist"=>Dict{String,Any}("NAM_TEB"=>Dict{String,Any}(),"NAM_SSOn"=>Dict{String,Any}())),"Interpol_ec_sst"=>Dict{String,Any}()),"Addsurf"=>Dict{String,Any}()))))
