#!/usr/bin/env julia

"""
   isvalid filename
"""
mydir=@__DIR__

using JSON 
using JSONSchema

schemafile="$mydir/harmonie.schema.json"

if size(ARGS,1) <=1 
   configfile = ARGS[1] 
else
 configfile= "$mydir/config_exp.json"
end 

println("Checking $configfile against schema $schemafile") 


schema = JSON.parsefile(schemafile)

schema["\$id"]  = "$mydir/schema" # point "$id" to disk instead of url 

myschema = Schema(schema)
  
config = JSON.parsefile(configfile)


g  = diagnose(config,myschema) 

if g == nothing 
   exit(0) 
else 
   error(g) 
end
#if isvalid(config,myschema)  
#  exit(0)
#else 
#  exit(1)
# end 
 



