[CLIMATE_SIMULATION.FORECAST]
ENSMSEL = []
PHYSICS = "arome"
DYNAMICS = "nh"
HWRITUPTIMES = "00-760:6"
FULLFAFTIMES = "00-760:24"
PWRITUPTIMES = "00-760:6"
VERITIMES = "00-760:6"
SFXSELTIMES = "00-760:6"
SWRITUPTIMES = "00-760:12"
SFXWFTIMES = "00-760:12"


