[GENERAL]
DESCRIPTION="Derive structure functions for AROME 3DVAR"
FESTAT=yes
HH_LIST="00,12"
LL_LIST="06"

[GEOMETRY]
DOMAIN="DKCOEXP"
VLEV="65"

[NESTING]
BDSTRATEGY="enda"
HOST_MODEL="ifs"
BDINT=1

[OBSERVATIONS]
OBSEXTR="no"
FLDEXTR="no"
OBSMONITOR="no"

[INITIAL_CONDITIONS]
ANAATMO="none"
LSMIXBC="no"
ANASURF="none"
DFI="none"

[FORECAST]
ENSMSEL=[1, 2, 3, 4]
PHYSICS="arome"
DYNAMICS="nh"

[ECMWWF]
ECFSLOC="ec"

[EPS]
ENSINIPERT="bnd"

[EPS.MEMBER_SETINGS]
ENSBDMBR={ 1=1, 2=2, 3=3, 4=4}
ENSCTL={ 1="001", 2="002", 3="003", 4="004"}
SLAFLAG={ 1=0, 2=0, 3=0, 4=0}

