[LETKF.GENERAL]
DESCRIPTION = "Standard 3D LETKF AROME settings"
HH_LIST = "0-21:3"
LL_LIST = "03"

[LETKF.GEOMETRY]
DOMAIN = "DKCOEXP"
VLEV = "65"

[LETKF.NESTING]
HOST_MODEL = "ifs"

[LETKF.INITIAL_CONDITIONS]
ANAATMO = "LETKF"
DFI = "none"
ANASURF = "CANARI"
ANASURF_MODE = "after"
NOUTERLOOP = 1
CH_RES_SPEC = "no"
BDINT = 1
BDSTRATEGY = "simulate_operational"
LETKF_LAG = "no"
LSMIXBC = "no"

[LETKF.FORECAST]
ENSMSEL = [0, 1, 2, 3, 4]
PHYSICS = "arome"
DYNAMICS = "nh"
HWRITUPTIMES = "00-03:1"
PWRITUPTIMES = "00-03:1"
PFFULLWFTIMES = "00-03:1"
VERITIMES = "00-03:1"
SFXWFTIMES = "00-03:1"

[LETKF.EPS]
ENSINIPERT = "none"
PERTSURF = "ECMA"

