[GENERAL}
DESCRIPTION = "Standard AROME settings 4DVAR"
HH_LIST="0-21:3"

[GEOMETRY]
DOMAIN="DKCOEXP"
VLEV="65"

[NESTING]
BDSTRATEGY = "simulate_operational"
BDINT=1
HOST_MODEL="ifs"

[INITIAL_CONDITIONS]
ANAATMO="4DVAR"
LSMIXBC="no"
ANASURF="CANARI"
ANASURF_MODE="after"
DFI="none"

[FORECAST]
ENSMSEL = []
LGRADSP = false
LUNBC = false
STATNW = false
HARATU = false
HWRITUPTIMES = "00-21:1,24-60:6"
PHYSICS="arome"
DYNAMICS="nh"

[EPS]
ENSINIPERT="none"
