SURFEX_LSELECT = "no"
HOST_MODEL = "ala"
PLAYFILE = "musc"
BDSTRATEGY = "available"
ANAATMO = "none"
BDDIR = "$HM_DATA/../EXP/archive_ALARO/@YYYY@/@MM@/@DD@/@HH@/"
config = "ALARO"
ANASURF = "none"
BDCLIM = ""
DOMAIN = "MUSC"
HOST_SURFEX = "yes"
