config = "AROME"
ANAATMO = "none"
BDDIR = "$HM_DATA/../EXP/archive_AROME_NONE/@YYYY@/@MM@/@DD@/@HH@/"
HOST_SURFEX = "yes"
DOMAIN = "TEST_8"
ANASURF = "none"
BDLIB = "AROME_NONE"
BDCLIM = "$HM_DATA/../EXP/climate/TEST_11"
HOST_MODEL = "aro"
BDSTRATEGY = "available"
BDINT = "1"
