LISBA_CANOPY = ".FALSE."
HOST_MODEL = "aro"
BDINT = "3"
NPATCH = "2"
BDSTRATEGY = "same_forecast"
CLIMDIR = "$HM_DATA/../EXP/climate/$DOMAIN/2P"
BDDIR = "$HM_DATA/../EXP/archive_AROME_3DVAR_2P/@YYYY@/@MM@/@DD@/@HH@/"
ANAATMO = "none"
BDCYCLE = "3"
config = "AROME_3DVAR"
BDCLIM = "$HM_DATA/../EXP/climate/TEST_11/2P/"
BDLIB = "AROME_3DVAR_2P"
ANASURF = "none"
HOST_SURFEX = "yes"
DOMAIN = "TEST_8"
