[TESTBED]
DESCRIPTION = "AROME 3DVAR with observations from MARS"
"CONFIGURATION" = "AROME_3DVAR"

[PROGRESS]
"DTG" = "2018081818"
"DTGEND" = "2018081921"

[GENERAL]
"LL_LIST" = "3"

[GEOMETRY]
"DOMAIN" = "IRELAND150"
"VLEV" = "HIRLAM_60"

[OBSERVATIONS]
OBDIR_PATTERN = "TODO 'OBDIR'}.'/mars"
USEOBSOUL = "0"
EPROF_OBS = "1"
AMSUA_OBS = "1"
AMSUA_SOURCE = "mars"
AMSUB_OBS" = "1"
AMSUB_SOURCE" = "mars"
IASI_OBS" = "0"
IASI_SOURCE" = "mars"
SCATT_OBS" = "0"
SCATT_SOURCE" = "mars"
HIRS_OBS" = "0",
HIRS_SOURCE" = "mars"
ATMS_OBS" = "0"
ATMS_SOURCE" = "mars"
CRIS_OBS" = "0"
CRIS_SOURCE" = "mars"
SEV_OBS" = "0"
SEV_SOURCE" = "mars"
RADAR_OBS" = "0"
GNSS_OBS" = "0"
MAKEODB2" = "yes"
VARBC_COLD_START" = "yes"

