HOST_MODEL = "ala"
BDINT = "1"
BDSTRATEGY = "available"
ANAATMO = "none"
BDDIR = "$HM_DATA/../EXP/archive_ALARO_NONE/@YYYY@/@MM@/@DD@/@HH@/"
config = "AROME"
BDLIB = "ALARO_NONE"
ANASURF = "none"
BDCLIM = "$HM_DATA/../EXP/climate/"
DOMAIN = "TEST_8"
HOST_SURFEX = "yes"
