[TESTBED]
DESCRIPTION = ""
CONFIGURATION = "AROME"

[GENERAL]

[DOMAIN]
DOMAIN = "TEST_8"

[NESTING]
BDSTRATEGY = "same_forecast"
BDCLIM = "$HM_DATA/../EXP/climate/TEST_11/arome/"
BDLIB = "AROME"
BDDIR = "$HM_DATA/../EXP/archive_AROME/@YYYY@/@MM@/@DD@/@HH@/"
BDCYCLE = "3"
BDINT = "3"
IO_SERVER_BD = "yes"
HOST_MODEL = "aro"
HOST_SURFEX = "yes"


[INITIAL_CONDITIONS]
ANASURF = "none"
ANAATMO = "none"


[FORECAST]
TFLAG = "min"
IO_SERVER = "yes"
SFXSELTIMES = "0-360:15"
ARCHIVE_FORMAT = "GRIB2"
SWRITUPTIMES = "0-360:180"
SFXWFTIMES = "0-360:180"
HWRITUPTIMES = "0-360:30"
FULLFAFTIMES = "0-360:180"
PFFULLWFTIMES = "0-360:60"


[VERIFICATION]
FLDEXTR_TASKS = "2"
VERITIMES = "0-360:60"

