[TESTBED]
DESCRIPTION = "AROME 3DENVAR"
CONFIGURATION = "AROME_3DENVAR"

[PROGRESS]
DTGEND = "2019050106"
DTG = "2019050100"

[GEOMETRY]
DOMAIN = "IRELAND150"
VLEV = "HIRLAM_60"

[NESTING]
BDSTRATEGY = "enda"


[GENERAL]
LL_LIST = "6"
HH_LIST = "00-18:6"

[FORECAST]
ENSMSEL = "0-3"

