DOMAIN = "TEST_2.5"
HOST_SURFEX = "yes"
BDLIB = "AROME_BD_ALA"
BDCLIM = "$HM_DATA/../EXP/climate/TEST_8"
config = "AROME"
BDDIR = "$HM_DATA/../EXP/archive_AROME_BD_ALA/@YYYY@/@MM@/@DD@/@HH@/"
BDSTRATEGY = "available"
BDINT = "1"
HOST_MODEL = "aro"
