HOST_MODEL = "ala"
BDSTRATEGY = "same_forecast"
BDINT = "3"
config = "AROME"
ANAATMO = "none"
BDCYCLE = "3"
BDDIR = "$HM_DATA/../EXP/archive_ALARO/@YYYY@/@MM@/@DD@/@HH@/"
HOST_SURFEX = "yes"
DOMAIN = "TEST_8"
BDLIB = "ALARO"
ANASURF = "none"
BDCLIM = "$HM_DATA/../EXP/climate/TEST_11/alaro/"
