[TESTBED]
"CONFIGURATION" = "AROME_3DVAR"

[PROGRESS]
"DTG" = "2018081818"
"DTGEND" = "2018081921"

[GENERAL]
"LL_LIST" = "3"

[GEOMETRY]
"DOMAIN" = "IRELAND150"
"VLEV" = "HIRLAM_60"

[OBSERVATIONS]
USEOBSOUL = "0"
EPROF_OBS = "1"
AMSUA_OBS = "1"
AMSUA_SOURCE = "ears"
AMSUB_OBS" = "1"
AMSUB_SOURCE" = "ears"
IASI_OBS" = "1"
IASI_SOURCE" = "ears"
SCATT_OBS" = "1"
SCATT_SOURCE" = "ears"
HIRS_OBS" = "1",
HIRS_SOURCE" = "ears"
ATMS_OBS" = "0"
ATMS_SOURCE" = "ears"
CRIS_OBS" = "0"
CRIS_SOURCE" = "ears"
SEV_OBS" = "1"
SEV_SOURCE" = "ears"
RADAR_OBS" = "0"
GNSS_OBS" = "0"
MAKEODB2" = "yes"
VARBC_COLD_START" = "yes"

