ANAATMO = "4DVAR"
config = "AROME_4DVAR"
DOMAIN = "SCANDINAVIA"
DTGEND = "2019100106"
DTG = "2019100100"
HWRITUPTIMES = ""00-06:1""
LL_LIST = "3"
OBSMONITOR = "plotlog"
SWRITUPTIMES = ""00-06:1""
VLEV = "HIRLAM_60"
