[TESTBED]
DESCRIPTION = "Basic HARMONIE EPS forecast"
CONFIGURATION = "AROME"

[GENERAL]
LL_LIST = "06"

[NESTING]
INT_BDFILE = "$WRK/ELSCF${CNMEXP}ALBC@NNN@"
BDSTRATEGY = "simulate_operational"
INT_SINI_FILE = "$WRK/SURFXINI.fa"
HOST_MODEL = "ifs"

[OBSERVATIONS]
OBSMONITOR = "no"

[INITIAL_CONDITIONS]
DFI = "none"

[FORECAST]
ENSMSEL = [0, 1, 2, 3]
ARCHIVE_FORMAT = "GRIB2"
PFFULLWTIMES = "00"
ARCHIVE_FORMAT = "GRIB2"

[EPS]
ENSINIPERT = "bnd"
PERTSURF = "model"

[VERIFICATION]
VERITIMES = "00-60:1"

