[TESTBED]
CONFIGURATION = "AROME"
DESCRIPTION = "Basic HARMONIE EPS forecast"

[PROGRESS]
DTG = "2019111021"
DTGEND = "2019111103"

[GENERAL]
LL_LIST = "06"

[NESTING]
HOST_MODEL = "ifs"
INT_SINI_FILE = "$WRK/SURFXINI.fa"
INT_BDFILE = "$WRK/ELSCF${CNMEXP}ALBC@NNN@"
BDSTRATEGY = "eps_ec_oper"
REARCHIVE_EPS_EC_OPER = "no"
ECFS_EPS_EC_BD_PATH = "ec:/hlam/testbed_data"

[OBSERVATIONS]
OBSMONITOR = "no"

[INITIAL_CONDITIONS]
DFI = "none"

[FORECAST]
ENSMSEL = [0, 1, 2, 3]
PFFULLWTIMES = "00"
ARCHIVE_FORMAT = "GRIB2"

[EPS]
PERTSURF = "model"
SPP = "yes"
SPPT = "yes"
ENSINIPERT = "bnd"

[EPS.MEMBER_SETTINGS]
ENSBDMBR = { 0 = 0, 1=1, 2 = 2}
SLAFLAG = { 0 = 0, 1=0, 2 = 0 }
SLAFDIFF = { 0 = 0, 1=0, 2 = 0 }

[VERIFICATION]
VERITIMES = "00-60:1"

